In [9]:
import h5py
import numpy as np
import torch
import tensorflow as tf

In [2]:
f = h5py.File("../../data/akita/valid.hdf5", "r")
print(list(f.keys()))
seq_data = f['sequences']
print(seq_data.shape)
tar_data = f['targets']
print(tar_data.shape)

['sequences', 'targets']
(419, 1048576)
(419, 99681, 5)


In [3]:
seq = torch.Tensor(seq_data[()])
tar = torch.Tensor(tar_data[()])

In [4]:
print(seq)

tensor([[2., 0., 0.,  ..., 0., 0., 3.],
        [0., 1., 0.,  ..., 3., 3., 0.],
        [0., 3., 0.,  ..., 1., 3., 3.],
        ...,
        [3., 1., 0.,  ..., 1., 1., 0.],
        [1., 3., 3.,  ..., 2., 0., 3.],
        [1., 3., 3.,  ..., 3., 3., 3.]])


In [5]:
print(tar)

tensor([[[-0.0573,  0.0027, -0.0147, -0.0372,  0.0585],
         [-0.0884, -0.0197, -0.0351, -0.1368,  0.1323],
         [-0.0039, -0.0434, -0.0548, -0.2234,  0.1765],
         ...,
         [-0.0069, -0.1243, -0.0491,  0.0170, -0.1730],
         [-0.1125, -0.1099, -0.1255,  0.0945, -0.2759],
         [-0.1224, -0.0768, -0.1875,  0.0518, -0.1003]],

        [[ 0.0995,  0.0663,  0.0287,  0.1210,  0.0715],
         [ 0.1407,  0.0872,  0.0074,  0.1757,  0.0502],
         [ 0.1504,  0.0494,  0.0079,  0.2194,  0.0269],
         ...,
         [ 0.0440,  0.0157,  0.0088, -0.0073, -0.0138],
         [ 0.0219,  0.0285, -0.0240, -0.0294, -0.0861],
         [ 0.0073,  0.0354, -0.0087, -0.0285, -0.0419]],

        [[ 0.0098,  0.0356,  0.0197, -0.0266, -0.1025],
         [ 0.0156,  0.0354,  0.0267, -0.0968, -0.2283],
         [-0.0066,  0.0147, -0.0037, -0.2394, -0.3098],
         ...,
         [ 0.0764, -0.0067,  0.0254,  0.0820,  0.0352],
         [ 0.1405, -0.0387,  0.0441,  0.1346,  0.0611],
  

In [ ]:
f.close()

In [25]:
l = [[4, 3, 2 , 6], [7, 3, 5, 7]]
print(tf.gather(l, [3, 2, 1, 0], axis=-1))
print(torch.randn())

tf.Tensor(
[[6 2 3 4]
 [7 5 3 7]], shape=(2, 4), dtype=int32)


TypeError: randn() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
